### ISSUE TITLE
ClassNotFoundException error

### ISSUE THREAD

**Issue by MasoodFallahpoor** [victorminerva/AutoResizeEditText#2]
I get the following error when a layout that contains a AutofitEdittext is being inflated.
`
java.lang.ClassNotFoundException: Didn't find class "com.victorminerva.widget.edittext.R$styleable"
`

**Comment by victorminerva** [comment]
Hello, could you show me your xml and java code?

2017-12-12 3:09 GMT-03:00 Masood Fallahpoor <notifications@github.com>:

**Comment by MasoodFallahpoor** [comment]
The layout is pretty simple. It just contains the EditText

```xml
<?xml version="1.0" encoding="utf-8"?>
<LinearLayout
    xmlns:android="http://schemas.android.com/apk/res/android"
    xmlns:app="http://schemas.android.com/apk/res-auto"
    xmlns:tools="http://schemas.android.com/tools"
    android:id="@+id/name_entry_root_layout"
    android:layout_width="match_parent"
    android:layout_height="match_parent">

        <com.victorminerva.widget.edittext.AutofitEdittext
            android:id="@+id/customer_name_edit_text"
            android:layout_width="match_parent"
            android:layout_height="wrap_content"
            android:background="@drawable/background_text_view"
            android:gravity="center"
            android:hint="@string/hint_your_name"
            android:maxLength="30"
            android:maxLines="1"
            android:padding="@dimen/space_medium"
            android:textColor="@android:color/black"
            android:textSize="46sp"/>

</LinearLayout>
```

The Activity that uses the above layout and does nothing fancy just a layout inflation is done in its onCreate and that's it.

**Comment by victorminerva** [comment]
Hello!
I copied and paste your code and the app it worked normally. So, could you remove the `android:background="@drawable/background_text_view"` and try again?

**Comment by MasoudFallahpour** [comment]
When I add the source code of your library as a module and use something like `compile project(":autoresizeedittext")` my app works. I think the AAR published on JCenter is missing something. Your sample app is working because it's using `compile project(":autoresizeedittext")`. Try `compile 'com.github.victorminerva:AutoResizeEditText:0.1.0'` and I think it fails.

**Comment by victorminerva** [comment]
Sorry, but I use this lib in another project, not as a module and it works normally:

See this build.gradle of another project:
https://github.com/victorminerva/emprestei/blob/develop/app/build.gradle

**Comment by MasoudFallahpour** [comment]
Sounds weird. I also removed `android:background="@drawable/background_text_view"` and it still crashes.

**Comment by victorminerva** [comment]
I showed my build.gradle because I would like you to see the SDK compatible versions

**Comment by victorminerva** [comment]
Hello, how are you?

I would like to know if you got to resolve the problem... cause I'm intrigued by such a failure.

**Comment by MasoudFallahpour** [comment]
I'm going to remove the background of EditText to see if it works. I'll
report back the result.

**Comment by MasoudFallahpour** [comment]
I copied the following code from README and pasted it into my layout and still the same error occurs.
```xml
<com.victorminerva.widget.edittext.AutofitEdittext
    android:layout_width="match_parent"
    android:layout_height="wrap_content"
    android:background="@android:color/transparent"
    android:maxLength="50"
    android:maxLines="2"
    android:padding="8dp"
    android:textSize="44sp"/>
```
